#!/usr/bin/env python3

import argparse
import hashlib
import os
import subprocess
import sys
import tempfile
import textwrap

REALFILE = os.path.realpath(__file__)
INSTALL_DIR = os.path.join(os.path.dirname(REALFILE), "Xilinx")
BIN_DIR = "Vivado/2023.2/bin"
DIGEST_2023_2 = "ea98fc804c6fb074c1ea8c672d2bda728f79e6fa"


def main():
    try:
        progname = os.path.basename(sys.argv[0])
        if progname != "container-vivado":
            run(argparse.Namespace(command=[progname] + sys.argv[1:]))
            sys.exit(0)

        p = argparse.ArgumentParser()
        p.set_defaults(cmd=None)
        subparsers = p.add_subparsers(dest="cmd")

        p_setup = subparsers.add_parser("setup")
        p_setup.set_defaults(cmd=setup)
        p_setup.add_argument("installer")

        p_image = subparsers.add_parser("image")
        p_image.set_defaults(cmd=image)

        p_install = subparsers.add_parser("install")
        p_install.set_defaults(cmd=install)
        p_install.add_argument("installer")

        p_link = subparsers.add_parser("link")
        p_link.set_defaults(cmd=link)

        p_run = subparsers.add_parser("run")
        p_run.set_defaults(cmd=run)
        p_run.add_argument("command", nargs=argparse.REMAINDER)

        # Parse and execute
        args = p.parse_args()
        if not args.cmd:
            p.print_usage()
            sys.exit(1)
        args.cmd(args)
    except subprocess.CalledProcessError as e:
        sys.exit(e.returncode)
    except KeyboardInterrupt:
        sys.exit(130)


def setup(args):
    image(args)
    install(args)
    link(args)


def image(args):
    docker(
        "build",
        "--platform=linux/amd64",
        "--tag=x64-linux",
        f"--build-arg=PACKAGES={" ".join(PACKAGES)}",
        "-",
        input=DOCKERFILE,
        encoding="utf-8",
    )


def install(args):
    with open(args.installer, "rb") as f:
        digest = hashlib.sha1(f.read()).hexdigest()
    if digest != DIGEST_2023_2:
        print(f"{args.installer}: digest mismatch")
        exit(1)

    installer = os.path.realpath(args.installer)
    os.makedirs(INSTALL_DIR, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix=INSTALL_DIR) as tmpdir:

        def docker_run(command, **kwds):
            args = (
                ["run", "--rm", "--platform=linux/amd64"]
                + (["--tty", "--interactive"] if sys.stdin.isatty() else [])
                + [
                    f"--mount=type=bind,source={tmpdir},target=/home/user",
                    f"--mount=type=bind,source={INSTALL_DIR},target=/home/user/Xilinx",
                    f"--mount=type=bind,source={installer},target=/home/user/install",
                    "--workdir=/home/user",
                    "x64-linux",
                    "sudo",
                    "--user=user",
                    "--set-home",
                ]
                + command
            )
            docker(*args, **kwds)

        docker_run(
            [
                "sh",
                "-c",
                "eval /home/user/install --target /home/user/installer --noexec",
            ],
            check=False,
        )

        with open(os.path.join(tmpdir, "config.txt"), "w") as f:
            f.write(INSTALL_CONFIG)
        docker_run("installer/xsetup -b AuthTokenGen".split())
        docker_run(
            "installer/xsetup -b Install -c /home/user/config.txt -a XilinxEULA,3rdPartyEULA".split()
        )


def link(args):
    for binary in BINARIES:
        try:
            os.symlink(REALFILE, os.path.join(os.path.expanduser("~/.local/bin"), binary))
            print(f"link {binary}")
        except FileExistsError:
            print(f"skip {binary}")


def run(args):
    cur_dir = os.getcwd()
    git_work_dir = subprocess.run(
        "git rev-parse --show-toplevel".split(),
        capture_output=True,
        encoding="utf-8",
    )
    if git_work_dir.returncode != 0:
        print("not in a git repository")
        sys.exit(1)
    git_work_dir = git_work_dir.stdout[:-1]

    assert args.command
    command = f"/home/user/Xilinx/{BIN_DIR}/{args.command[0]}"

    docker(
        *["run", "--rm", "--platform=linux/amd64"]
        + (["--tty", "--interactive"] if sys.stdin.isatty() else [])
        + [
            f"--mount=type=bind,source={INSTALL_DIR},target=/home/user/Xilinx",
            f"--mount=type=bind,source={git_work_dir},target={git_work_dir}",
            f"--workdir={cur_dir}",
            "x64-linux",
            "sudo",
            "--user=user",
            "--set-home",
            "env",
            "LD_PRELOAD=/lib/x86_64-linux-gnu/libudev.so.1",
        ]
        + [command]
        + args.command[1:]
    )


def docker(*args, check=True, **kwds):
    subprocess.run(["docker"] + list(args), check=check, **kwds)


DOCKERFILE = """
FROM --platform=linux/amd64 ubuntu:22.04
ARG PACKAGES

RUN apt-get update \\
        && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends $PACKAGES \\
        && apt-get upgrade -y \\
        && rm -rf /var/lib/apt/lists/*

RUN useradd --create-home --shell /bin/bash --user-group --groups adm,sudo user \\
        && chown -R user:user /home/user

RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen && locale-gen
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV LD_PRELOAD="/lib/x86_64-linux-gnu/libudev.so.1"
""".lstrip()

PACKAGES = [
    "curl",
    "gnupg",
    "ca-certificates",
    "sudo",
    "nano",
    "python3-pip",
    "python3-dev",
    "build-essential",
    "git",
    "gcc-multilib",
    "g++",
    "ocl-icd-opencl-dev",
    "libjpeg62-dev",
    "libc6-dev-i386",
    "graphviz",
    "make",
    "unzip",
    "libtinfo5",
    "xvfb",
    "libncursesw5",
    "locales",
    "libswt-gtk-4-jni",
]

INSTALL_CONFIG = """
#### Vivado ML Standard Install Configuration ####
Edition=Vivado ML Standard

Product=Vivado

# Path where AMD FPGAs & Adaptive SoCs software will be installed.
Destination=/home/user/Xilinx

# Choose the Products/Devices the you would like to install.
Modules=Virtex UltraScale+ HBM:1,Kintex UltraScale:1,Vitis Networking P4:0,Artix UltraScale+:1,Spartan-7:1,Artix-7:1,Virtex UltraScale+:1,Vitis Model Composer(Toolbox for MATLAB and Simulink. Includes the functionality of System Generator for DSP):1,DocNav:1,Zynq UltraScale+ MPSoC:1,Zynq-7000:1,Virtex UltraScale+ 58G:1,Vitis Embedded Development:0,Kintex-7:1,Install Devices for Kria SOMs and Starter Kits:1,Kintex UltraScale+:1

# Choose the post install scripts you'd like to run as part of the finalization step. Please note that some of these scripts may require user interaction during runtime.
InstallOptions=

## Shortcuts and File associations ##
# Choose whether Start menu/Application menu shortcuts will be created or not.
CreateProgramGroupShortcuts=1

# Choose the name of the Start menu/Application menu shortcut. This setting will be ignored if you choose NOT to create shortcuts.
ProgramGroupFolder=Xilinx Design Tools

# Choose whether shortcuts will be created for All users or just the Current user. Shortcuts can be created for all users only if you run the installer as administrator.
CreateShortcutsForAllUsers=0

# Choose whether shortcuts will be created on the desktop or not.
CreateDesktopShortcuts=1

# Choose whether file associations will be created or not.
CreateFileAssociation=1

# Choose whether disk usage will be optimized (reduced) after installation
EnableDiskUsageOptimization=1
""".lstrip()

BINARIES = ["vivado"]

if __name__ == "__main__":
    main()
